#' Calculate the rate of host-repertoire evolution
#'
#' Calculate the number of host gains, host losses, and the
#'   effective rate of host repertoire evolution
#' @param history A data frame containing the character history produced by
#'   RevBayes
#' @param tree A phylogenetic tree of the parasite clade
#'
#' @examples
#' # read parasite tree
#' data(tree)
#'
#' # read hist
#' data(history)
#'
#' # remove burnin and thin samples
#' it_seq <- seq(10000,100000,1000)
#' history <- dplyr::filter(history, iteration %in% it_seq)
#'
#' # effective rate
#' n_events <- count_events(history)
#' rate <- effective_rate(history,tree)
#'
#' # gains and losses
#' gl_events <- count_gl(history)
#' gl_rates <- rate_gl(history, tree)
#'
#' @name events_counter
NULL

#' @describeIn events_counter Get the total number of events along the parasite tree
#' @export
count_events <- function(history){
  if (!is.data.frame(history)) {
    stop('`history` should be a data.frame, usually generated by `read_history()`')
  }
  if (!all(c('node_index', 'iteration', 'transition_type') %in% names(history))) {
    stop('`history` needs to have columns `node_index`, `iteration` and `transition_type`.')
  }

  root <- max(history$node_index)
  transitions <- sum(history$transition_type[history$node_index < root] == 'anagenetic')
  iters <- dplyr::n_distinct(history$iteration)
  n_events <- transitions / iters

  n_events
}


#' @describeIn events_counter Get the effective rate of evolution, i.e. number
#'   of events per million years, along each tree branch
#' @export
effective_rate <- function(history, tree) {
  # history will be checked in count_events
  if (!inherits(tree, 'phylo')) stop('`tree` should be a phylogeny of class `phylo`.')

  nev <- count_events(history)
  tree_length <- sum(tree$edge.length)
  rate <- nev/tree_length

  rate
}


#' @describeIn events_counter Get the number of host gains and host losses
#' @export
count_gl <- function(history) {
  if (!is.data.frame(history)) {
    stop('`history` should be a data.frame, usually generated by `read_history()`')
  }
  if (!all(c('node_index', 'iteration', 'transition_type', 'start_state', 'end_state')
           %in% names(history))) {
    stop('`history` needs to have columns `node_index`, `iteration`, `transition_type`, `start_date` and `end_date`.')
  }

  root <- max(history$node_index)

  filtered_history <- history %>%
    dplyr::filter(transition_type == "anagenetic", node_index < root) %>%
    dplyr::select(iteration, start_state, end_state)

  # str_split_fixed creates a matrix of size [n_chars, n_obs]
  str_size <- stringr::str_length(filtered_history$start_state[1])
  starts <- stringr::str_split_fixed(filtered_history$start_state, "", str_size)
  ends   <- stringr::str_split_fixed(filtered_history$end_state,   "", str_size)

  # Change to numeric:
  storage.mode(starts) <- storage.mode(ends) <- 'numeric'

  # Compare the sums
  start_sums <- rowSums(starts)
  end_sums   <- rowSums(ends)
  gains <- sum(end_sums > start_sums)
  loss  <- sum(end_sums < start_sums)

  iters <- dplyr::n_distinct(filtered_history$iteration)

  ngains <- gains / iters
  nloss  <- loss  / iters

  gl <- c(ngains, nloss)
  names(gl) <- c("gains","losses")

  gl
}


#' @describeIn events_counter Get the effective rate of host gain and host loss
#' @export
rate_gl <- function(history, tree) {
  # history will be checked in count_gl
  if (!inherits(tree, 'phylo')) stop('`tree` should be a phylogeny of class `phylo`.')

  gl <- count_gl(history)
  tree_length <- sum(tree$edge.length)
  rg <- gl[1]/tree_length
  rl <- gl[2]/tree_length

  rgl <- c(rg,rl)
  names(rgl) <- c("gain_rate","loss_rate")

  rgl

}


iteration <- transition_type <- node_index <- n <- start_state <- end_state <- type <- NULL
